export const LOAD_FLIGHTS_SUCCESS = "LOAD_FLIGHTS_SUCCESS";
export const UPDATE_FLIGHTS_SUCCESS = "UPDATE_FLIGHTS_SUCCESS";
export const LOAD_USER_ROLES_SUCCESS = "LOAD_USER_ROLES_SUCCESS";
export const LOAD_CURRENT_USER_SUCCESS = "LOAD_CURRENT_USER_SUCCESS";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";

